### ISSUE TITLE
Build non-latest Docker image

### ISSUE THREAD

**Issue by karlkfi** [cytopia/docker-goimports#6]
Docker shows these tags:
- latest
- latest-
- latest-0.1
- latest-release-0.1

I would expect a non-latest, versioned image in Docker Hub, like `0.1`.

**Comment by cytopia** [comment]
@karlkfi thanks for the info, I wasn't aware of this.

**Comment by cytopia** [comment]
@karlkfi I just double checked and the way it currently is, is correct.

* `latest` (latest goimports version, latest push from master branch)
* `latest-0.1` (latest goimports version, push from git tag `0.1`)
* `latest-release-0.1` (latest goimports version, push from branch `release-0.1`)

This is an implementation to allow specific goimports versions to be added:

* `0.78` (This would refer to goimports version 0.78)
* `latest-0.78` (same as above)
* `0.78-0.1` (goimports version 0.78 push from git tag 0.1)


Hope thta clarifies it.
