### ISSUE TITLE
Add Option to accept list of files

### ISSUE THREAD

**Issue by sp71** [cytopia/docker-goimports#8]
**DESCRIPTION**
* Its often to not format all files
* Example: vendor folder, protobuf generated files, etc

**REQUEST**
* Add an option where the image accepts a list of files to process
* Or provide options to ignore vendor and/or protobuf generated files since they are used often

**WORKAROUND**
* Running `docker run`  on each file is much slower with this workaround

```
#!/bin/bash

files=$(find . -type f -name "*.go" | grep -v vendor | grep -v pb.go)
for f in $files; do
    diff=$(docker run --rm -v $(pwd):/data cytopia/goimports -d $f)
    if [[ "$diff" != "" ]]; then
        echo "File fails goimports linter: $f"
        exit 2
    fi
done
```

**Comment by cytopia** [comment]
@sp71 Is that not provided by default by goimports? How do you ususally do that if you run the binary locally?

**Comment by sp71** [comment]
It's not a default behavior but should be since proto, vendor, etc should be ignored. I created a custom Dockerfile and shell script so it would be much quicker on any CI. It will be great if you can incorporate this behavior into your own script. Otherwise, the current solution with your image is to spin up the docker image every time for every file.

**Dockerfile**

```
FROM golang:1.14

COPY . /go/src/github.com/repo
RUN cd /go/src/github.com/repo
RUN go get golang.org/x/tools/cmd/goimports
COPY ./scripts/lint_go.sh /lint_go.sh
WORKDIR /go/src/github.com/repo/

ENTRYPOINT ["/lint_go.sh"]
```

**lint_go.sh**

```

#!/bin/bash

files=$(find . -type f -name "*.go" | grep -v vendor | grep -v pb.go)
for f in $files; do
    diff=$(goimports -d $f)
    if [[ "$diff" != "" ]]; then
        echo "Linter detected error for file: $f"
        echo "Developer needs to ensure code follows linting rules"
        exit 2
    fi
done
```

**Comment by sp71** [comment]
@cytopia

**Comment by Yscream** [comment]
any solutions?

**Comment by darkdragon-001** [comment]
I proposed #11. Can you try if this fixes the problem?

**Comment by sp71** [comment]
Another tool that offers functionality

https://github.com/incu6us/goimports-reviser

**Comment by sp71** [comment]
Been a few years with no progress so closing out issue
